#!/usr/bin/env ansible-playbook
---
- name: Installing ansible python library using Ansible pip module and symlinking to HOME/bin
  pip:
    chdir: "~"
    executable: "~/bin/pip"
    name: "ansible"
- name: Creating Symlinks for the Ansible Commands
  file:
    src: "~/.ansible/pypy/bin/{{ item }}"
    dest: "~/bin/{{ item }}"
    state: link
  with_items: [ "ansible", "ansible-connection", "ansible-doc",
    "ansible-inventory", "ansible-pull", "ansible-config",
    "ansible-console", "ansible-galaxy", "ansible-playbook",
    "ansible-vault" ]
