#!/usr/bin/env ansible-playbook
---

- name: Playbook to download dynamic ansible_plugins_inventory_url plugins
  hosts: localhost
  vars:
    local_home: "{{ ansible_env.HOME }}"
    local_user: "{{ ansible_env.USER }}"
    ansible_inventory_path: "{{ local_home }}/ansible/inventory"
    ansible_library_path: "{{ local_home }}/ansible/library"
    ansible_files: "{{ local_home }}/ansible/files"
    ansible_keys: "{{ local_home }}/ansible/keys"
    ansible_templates: "{{ local_home }}/ansible/templates"
    ansible_inventory_path: "/etc/ansible/inventory"
    ansible_contrib_inventory_url: "https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory"
    ansible_plugins_inventory_url: "https://raw.githubusercontent.com/ansible/ansible/devel/lib/ansible/plugins/inventory/"
    azure_rm_resource_groups:
    azure_rm_locations:
    consul_io_url:
    openstack_cloud_name:
    openstack_auth_url:
    openstack_username:
    openstack_password:
    openstack_project_name:
    openstack_region_name:
    device42_user:
    device42_passwd:
    device42_url:
    netbox_api_endpoint:
  roles:
    # Install Azure python Dependencies from Azure/azure_modules
    - role: azure.azure_modules
  tasks:
  - name: "{{ ansible_inventory_path }}"
    file:
      path: "{{ ansible_inventory_path }}"
      state: directory
      mode: 0755

  - name: "{{ ansible_library_path }}"
    file:
      path: "{{ ansible_library_path }}"
      state: directory
      mode: 0755

  - name: "{{ ansible_files }}"
    file:
      path: "{{ ansible_files }}"
      state: directory
      mode: 0755

  - name: "{{ ansible_keys }}"
    file:
      path: "{{ ansible_keys }}"
      state: directory

  - name: consul_io.ini
    # get_url: 
      # url: "{{ ansible_contrib_inventory_url }}/consul_io.ini"
      # dest: "{{ ansible_inventory_path }}/consul_io.ini"
      # owner: "{{ local_user }}"
      # group: "{{ local_user }}"
      # mode: "0755"
    template:
      src: "{{ ansible_templates }}/consul_io.ini.j2"
      dest: "{{ ansible_contrib_path }}/consul_io.ini"
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: "0755"

  - name: consul_io.py
    get_url: 
      url: "{{ ansible_contrib_inventory_url }}/consul_io.py"
      dest: "{{ ansible_inventory_path }}/consul_io.py"
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: "0755"

  - name: azure_rm.ini
    #get_url: 
    #  url: "{{ ansible_plugins_inventory_url }}/azure_rm.ini"
    #  dest: "{{ ansible_inventory_path }}/azure_rm.ini"
    #  owner: "{{ local_user }}"
    #  group: "{{ local_user }}"
    #  mode: "0755"
    template:
      src: "{{ ansible_templates }}/azure_rm.ini.j2"
      dest: "{{ ansible_inventory_path }}/azure_rm.ini"
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: "0755"
  - name: azure_rm.py
    get_url: 
      url: "{{ ansible_plugins_inventory_url }}/azure_rm.py"
      dest: "{{ ansible_library_path }}/azure_rm.py"
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: "0755"

  - name: ec2.ini
    get_url: 
      url: "{{ ansible_plugins_inventory_url }}/ec2.ini"
      dest: "{{ ansible_inventory_path }}/ec2.ini"
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: "0755"
  - name: ec2.py
    get_url: 
      url: "{{ ansible_plugins_inventory_url }}/ec2.py"
      dest: "{{ ansible_inventory_path }}/ec2.py"
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: "0755"

  - name: docker.ini
    get_url: 
      url: "{{ ansible_plugins_inventory_url }}/docker.yml"
      dest: "{{ ansible_inventory_path }}/docker.yml"
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: "0755"
  - name: docker.py
    get_url: 
      url: "{{ ansible_plugins_inventory_url }}/docker.py"
      dest: "{{ ansible_inventory_path }}/docker.py"
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: "0755"

  - name: gce.ini
    get_url: 
      url: "{{ ansible_plugins_inventory_url }}/gce.ini"
      dest: "{{ ansible_inventory_path }}/gce.ini"
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: "0755"
  - name: gce.py
    get_url: 
      url: "{{ ansible_plugins_inventory_url }}/gce.py"
      dest: "{{ ansible_inventory_path }}/gce.py"
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: "0755"
  - name: openstack.yml
    template:
      src: "{{ ansible_templates }}/openstack.yml.j2"
      dest: "{{ ansible_inventory_path }}/openstack.yml"
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: "0755"
  - name: openstack_inventory.py
    get_url: 
      url: "{{ ansible_plugins_inventory_url }}/openstack_inventory.py"
      dest: "{{ ansible_inventory_path }}/openstack_inventory.py"
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: "0755"

  - name: vagrant.py
    get_url: 
      url: "{{ ansible_plugins_inventory_url }}/vagrant.py"
      dest: "{{ ansible_inventory_path }}/vagrant.py"
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: "0755"

  - name: netbox.py
    get_url: 
      url: "https://raw.githubusercontent.com/AAbouZaid/netbox-as-ansible-inventory/devel/netbox/netbox.py"
      dest: "{{ ansible_inventory_path }}/netbox.py"
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: "0755"
  - name: netbox.yml
    get_url: 
      url: "https://raw.githubusercontent.com/AAbouZaid/netbox-as-ansible-inventory/devel/netbox/netbox.yml"
      dest: "{{ ansible_inventory_path }}/netbox.yml"
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: "0755"

  - name: device42
    git:
      repo: https://github.com/device42/ansible_device42
      dest: "{{ ansible_inventory_path }}/device42"
      clone: yes
      update: yes
      force: yes

  - name: device42/conf
    template:
      src: "{{ ansible_templates }}/conf.device42.j2"
      dest: "{{ ansible_inventory_path }}/device42/conf"
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: "0755"

  - name: netbox_inventory.yml
    template:
      src: "{{ ansible_templates }}/netbox_inventory.yml.j2"
      dest: "{{ ansible_inventory_path }}/netbox_inventory.yml"
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: "0755"

  - name: Unifi Controller Facts Module
    git:
      repo: https://github.com/ppouliot/ansible_module-unifi_controller_facts.git
      dest: "{{ ansible_library_path }}/unifi_controller_facts"
      clone: yes
      update: yes
      force: yes

  - name: Ansible-Galaxy Install Requirements
    command: 'ansible-galaxy install -r requirements.yml --force'
    args:
      chdir: /etc/ansible
