#!/usr/bin/env molecule-playbook
---
- name: Install molecule ansible testing using pip and symlinking to HOME/bin
  pip:
    chdir: "~"
    executable: "~/bin/pip"
    name: "molecule"
- name: Creating Symlinks for the Molecule Commands
  file:
    src: "~/.molecule/pypy/bin/molecule"
    dest: "~/bin/molecule"
    state: link
