#!/usr/bin/env ansible-playbook
---
- name: Boot Strap User Account on Jumpbox to Run Ansible from Home Directory
#  hosts: jumpbox-by-ip
  hosts: jumpbox
  gather_facts: False
  any_errors_fatal: true
  roles:
    - role: ppouliot.container_linux_bootstrap


- name: Playbook to download and unpack Teraform Binaries from Hashicorp
  hosts: jumpbox
  gather_facts: True
  environment:
    PATH: "/home/peter.pouliot/bin:{{ ansible_env.PATH }}"
  tasks:

  - name: Unarchive a file that needs to be downloaded (added in 2.0)
    unarchive:
      src: "https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip"
      dest: /home/peter.pouliot/bin
      remote_src: yes

  - name: Download and install the minio binary to /home/peter.pouliot/bin
    get_url:
      url: "https://dl.minio.io/server/minio/release/linux-amd64/minio"
      dest: "/home/peter.pouliot/bin/minio"
      owner: "peter.pouliot"
      group: "peter.pouliot"
      mode: "0755"

  - name: Download and install the minio client (mc) binary to /home/peter.pouliot/bin
    get_url:
      url: "https://dl.minio.io/client/mc/release/linux-amd64/mc"
      dest: "/home/peter.pouliot/bin/mc"
      owner: "peter.pouliot"
      group: "peter.pouliot"
      mode: "0755"

  - name: Unarchive terraform and install to /home/peter.pouliot/bin
    unarchive:
      src: "https://github.com/adammck/terraform-inventory/releases/download/v0.8/terraform-inventory_v0.8_linux_amd64.zip"
      dest: /home/peter.pouliot/bin
      remote_src: yes

  - name: Unarchive atlantis and install to /home/peter.pouliot/bin
    unarchive:
      src: "https://github.com/runatlantis/atlantis/releases/download/v0.7.0/atlantis_linux_amd64.zip"
      dest: /home/peter.pouliot/bin
      remote_src: yes

  - name: Minio config
    template:
      src: "/etc/ansible/templates/etc_default_minio.j2"
      dest: "/home/peter.pouliot/minio.cfg"
      owner: "peter.pouliot"
      group: "peter.pouliot"
      mode: "0755"

  - name: Installing ansible python library using Ansible pip module and symlinking to HOME/bin
    pip:
      chdir: /home/peter.pouliot
      executable: /home/peter.pouliot/bin/pip
      name: ansible
  - file:
      src: "/home/peter.pouliot/.ansible/pypy/bin/{{ item }}"
      dest: "/home/peter.pouliot/bin/{{ item }}"
      state: link
    with_items:
      - "ansible"
      - "ansible-connection"
      - "ansible-doc"
      - "ansible-inventory"
      - "ansible-pull"
      - "ansible-config"
      - "ansible-console"
      - "ansible-galaxy"
      - "ansible-playbook"
      - "ansible-vault"

  - name: Unarchive goscan and install to /home/peter.pouliot/bin
    unarchive:
      src: "https://github.com/marco-lancini/goscan/releases/download/v2.4/goscan_2.4_linux_amd64.zip"
      dest: /home/peter.pouliot/bin
      remote_src: yes
